# frozen_string_literal: true
source "https://rubygems.org"

gem "sinatra-activerecord"
gem "sqlite3", '~> 1.4.0'
gem "pry"
gem "rake"
gem "require_all"
gem "faker"
gem 'activerecord', "~> 6.0.3"
gem 'tty-prompt'
